### ISSUE TITLE
Code for this tool

### ISSUE THREAD

**Issue by jlandure** [hanguokai/gdgstats#1]
Hi @hanguokai 👋 

First, thanks for the tool. I've used it for a long time and it's very valuable.

Did you have updated the code for this report tool?
Is this the good repository for [this app script](https://script.google.com/macros/s/AKfycbxhUrO0-2JUBpw60pc8JYt77PMESyex4b6-JNvopbTboV2JIaSL/exec)?

Have a good day. ☀️

**Comment by hanguokai** [comment]
@jlandure The online version of this tool still works and is maintained by me. But it changed a lot at backend to use meetup.com api since 2017.

The old version of this tool (before 2017), gets data from developers.google.com . Then google transfer to use meetup.com for GDG events and shutdown old data api. This repo is public and reflects the old version.

New version of this tool(since 2017) use [meetup api](https://www.meetup.com/meetup_api) to get data. Thus it contains meetup api key or secret key(for oauth) now. So I changed the online version of apps script project to private at that time. In Aug 2019, meetup stoped api key and ask all to use oauth (after Aug 2019, new applying for meetup oauth need meetup pro account). 

You can use meetup api directly now if convenient for you. Other questions for getting meetup data if I can help, you could contact me by my email.

**Comment by jlandure** [comment]
Hey @hanguokai 
Thanks for your response
Why not sharing your work (filling `blank` the meetup keys)? My goals is to create a similar tool but focus only on `GDG Cloud`.
